version: '3.6'
services:
  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: ems-elasticsearch
    restart: always
    volumes:
      - ems-elastic-data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk

  logstash:
    image: logstash:7.16.2
    container_name: ems-logstash
    restart: always
    volumes:
      - .logstash.conf/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  kibana:
    image: kibana:7.16.2
    container_name: ems-kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk
volumes:
  ems-elastic-data: {}

networks:
  elk: