server:
  port: 8080
  servlet:
    context-path: /v1/api

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/v1/api/event/**, /v1/api/organizer/**

management:
  endpoints:
    web:
      exposure:
        include: "*"