spring:
  application:
    name: event-service
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers_skip_column_definitions: 'true'
        globally_quoted_identifiers: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5441/ems-event
    password: postgres
  config:
    import: optional:file:.env[.properties]
server:
  port: 8081
